version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - java -version
      - mvn -v
      - ECR_REPO_URL=public.ecr.aws/v8y8p2w5/developeriq
  build:
    commands:
      - echo "Building Spring Boot Application..."
      - mvn clean install -DskipTests=true
  post_build:
    commands:
      - echo "Building Docker Image..."
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v8y8p2w5/developeriq
      - docker build -t public.ecr.aws/v8y8p2w5/developeriq:latest .
      - echo "Pushing Docker Image to ECR..."
      - docker push $public.ecr.aws/v8y8p2w5/developeriq:latest
      - echo "resolved version $CODEBUILD_RESOLVED_SOURCE_VERSION"
