version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Maven..."
      - yum install -y maven-3.9.6
      - mvn -v
      - ECR_REPO_URL=public.ecr.aws/v8y8p2w5/developeriq
  build:
    commands:
      - echo "Building Spring Boot Application..."
      - mvn clean install -DskipTests=true
  post_build:
    commands:
      - echo "Building Docker Image..."
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO_URL
      - docker build -t $ECR_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - echo "Pushing Docker Image to ECR..."
      - docker push $ECR_REPO_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
